version: '3.7'
services:
  redis:
    image: redis:5.0.0
    container_name: redis
    ports: ['6379:6379']
  elastic:
    image: elasticsearch:7.3.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  kibana:
    image: kibana:7.3.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
  logstash:
    image: logstash:7.3.0
    ports:
      - "9600:9600"
    environment:
      xpack.monitoring.elasticsearch.hosts: http://elastic:9200
    volumes:
      - ./logstash.conf:/logstash.conf
      - ./moviecatalog.log:/moviecatalog.log
      - ./commentservice.log:/commentservice.log
      - ./ratingservice.log:/ratingservice.log
      - ./servicediscovery.log:/servicediscovery.log
    command: logstash -f /logstash.conf
  db:
    image: mysql:8.0.19
    container_name: movie-db
    environment:
      MYSQL_DATABASE: 'movie-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports: ['3306:3306']
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"