version: '3.6'
services:
  redis:
    image: redis:5.0.0
    container_name: redis
    ports: ['6379:6379']
   
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    ports: ['9200:9200']
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: kibana
    ports: ['5601:5601']
    depends_on: ['elasticsearch']
      
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.0
    container_name: logstash
    ports: ['9600:9600']
    depends_on: ['elasticsearch']

  db:
    image: mysql:8.0.19
    container_name: movie-db
    environment:
      MYSQL_DATABASE: 'movie-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports: ['3306:3306']